source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

def shared_pods
    pod 'KeychainAccess'
    pod 'Kingfisher'
    pod 'OpenShare'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Alamofire'
    pod 'SnapKit'
    pod 'AlamofireObjectMapper'
    pod 'RxAlamofire'
    pod 'CryptoSwift'
    pod 'SwiftProgressHUD'
end

target 'TJFramework' do
    project 'TJFramework.xcodeproj'
    shared_pods
end
